---

#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Main variables
#

ift_user_name: ish
ift_user_shell: /bin/ash
ift_timezone: Europe/Amsterdam

# debian_reboot_if_needed: false

d_repo: /opt/ish-fstools

# wait_for_hosts_to_be_ready: false

#
#  This disables the wait for the host to be responsive
#  mostly useful for Vagrant nodes just after creation
#
# check_connection: false

#
#  I have tried to put the equivalent in ansible.cfg
#  but so far it never took effect. Avoiding host keys is
#  most useful when dealing with vagrant nodes that change
#  often. For iSH node it might not be needed, but since
#  they would normally only be accessed locally, it should
#  most likely not be an issue.
#
ansible_ssh_common_args:
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null


# if remote username does not match username on deploy host
ansible_user: root

# Default, will be overridden on cmd-line
target_hosts: servers

#
#  Defaults
#

ift_runlevel_runbg: sysinit

alpine_base_packages:
  #
  #  Shells
  #
  - bash
  - zsh
  - bash-completion
  - zsh-completions

  #
  #  Tools
  #
  - busybox-extras
  - coreutils
  - procps
  - util-linux
  - sudo
  - shadow
  - shadow-login
  - musl-locales
  - tzdata
  # - man-db
  - findutils
  - sed
  - tar
  - pigz
  - file
  - gawk
  - grep
  - htop
  - less
  - sqlite
  - py3-pip
  - ncdu
  # - fzf

  #
  #  Services
  #
  - openrc
  - dcron
  # - dcron-openrc

  #
  #  Networking Tools
  #
  - ssl_client
  - openssh
  # - git
  # - rsync
  - curl
  - wget
  - elinks
  - mosh
  - mtr

  #
  #  Editors
  #
  - vim
  - nano
  - mg
  - ed
  #
  #  Text-UI
  #
  - ncurses
  - newt
  - tmux
  - bat

  # =============

  #
  #  Other
  #
  # - fortune
alpine_version_dependent_packages:
  - lsb-release-minimal
ift_alpine_packages: "{{ alpine_base_packages +
  (alpine_version_dependent_packages
  if ansible_distribution_version is version('3.17', '>='))
  | default([]) }}"
