---

#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  User overrides
#
ift_user_name: jaclu
ift_timezone: Europe/Stockholm

ift_runlevel_runbg: default

# Default, will be overridden on cmd-line
target_hosts: servers
