#!/bin/sh
#
#  Part of https://github.com/jaclu/ish-fstool
#
#  License: MIT
#
#  Unfortunately the console session starts before the boot process has
#  completed. This means that the console will see the "old" version of
#  /etc/motd, might be mildly confusing if you have just upgraded to a
#  new Alpine release. Something like 1-2 seconds after this is displayed
#  on the console, the file is updated, so for ssh sessions, they will
#  always see the current content. If you are curious you can always do
#  a: cat /etc/motd
#  Otherwise just boot again, then it should have caught up.
#





#
#  Sample setup that displays release info
#

f_motd="/etc/motd"
f_motd_template="/etc/motd_template"
# alp_rel="$(grep VERSION_ID /etc/os-release | cut -d'=' -f2)"

# if [ -d /proc/ish ]; then
#     ish_rel="$(cat /proc/ish/version)"
# else
#     ish_rel="Can't be detected whilst chrooted"
# fi

#  create initial LF
echo >"$f_motd"

if [ -f "$f_motd_template" ]; then
    cat "$f_motd_template" >>"$f_motd"
fi

/usr/local/bin/ift-versions >>"$f_motd"

#(
#    echo "[35mAlpine release:  $alp_rel[0m"
#    echo "[35miSH release:     $ish_rel[0m"
#    echo
#) >>"$f_motd"

/usr/local/bin/logger update-motd updated /etc/motd
