---
# - name: Devuan /usr/local/bin
#   ansible.builtin.copy:
#     mode: preserve
#     src: /opt/AOK/Devuan/usr_local_bin/*
#     dst: /usr/local/bin

# - name: Devuan /usr/local/sbin
#   ansible.builtin.copy:
#     mode: preserve
#     src: /opt/AOK/Devuan/usr_local_sbin/*
#     dst: /usr/local/sbin

- name: Devuan packages
  ansible.builtin.package:
    mode: preserve
    name: "{{ packages_Devuan }}"
    state: present
