---

- name: Debian additional packages
  ansible.builtin.package:
    state: present
    name:

      #
      #  Tools
      #
      - psmisc
      - coreutils
      - util-linux
      - procps
      - sudo
      - grep
      - bc
      - file
      - gawk
      - sed
      - tar
      - pigz
      - less
      - tzdata
      - htop
      - sqlite3
      - fzf
      - python3-pip
      - ncdu

      #
      #  Networking Tools
      #
      - openssh-client
      - openssh-server
      - git
      - rsync
      - curl
      - wget
      - elinks
      - mosh

      #
      #  Shells
      #
      - bash
      - zsh

      #
      #  Services
      #
      - openrc
      - cron

      #
      #  Editing
      #
      - vim
      - nano
      - mg

      #
      #  Text UI
      #
      - ncurses-bin
      - whiptail
      - tmux

      #
      #  Other
      #
      # - fortune-mod
  when: ansible_facts.distribution == 'Debian'


- name: Alpine additional packages
  ansible.builtin.package:
    state: present
    name: "{{ additional_packages }}"
  vars:
    base_packages:
      #
      #  Tools
      #
      - busybox-extras
      - coreutils
      - procps
      - util-linux
      - sudo
      - shadow
      - shadow-login
      - tzdata
      - findutils
      - sed
      - tar
      - pigz
      - file
      - gawk
      - grep
      - htop
      - less
      - man-db
      - sqlite
      - fzf
      - py3-pip
      - ncdu
      #
      #  Networking Tools
      #
      - ssl_client
      - openssh
      - git
      - rsync
      - curl
      - wget
      - elinks
      - mosh
      #
      #  Shells
      #
      - bash
      - zsh
      #
      #  Services
      #
      - openrc
      - dcron
      - dcron-openrc
      #
      #  Editing
      #
      - vim
      - nano
      - mg
      #
      #  Text UI
      #
      - ncurses
      - newt
      - tmux
      #
      #  Other
      #
      # - fortune
    version_dependent_packages:
      - lsb-release-minimal
    additional_packages: "{{ base_packages +
      (version_dependent_packages
      if ansible_facts.distribution_version is version('3.17', '>='))
      | default([]) }}"
  retries: 3
  delay: 5
  when: ansible_facts.distribution == 'Alpine'
