---

- name: Dont use /bin/ash on Debian
  ansible.builtin.set_fact:
    aok_user_shell: "{{ '/bin/bash' if ansible_distribution == 'Debian' }}"
  when: aok_user_shell == '/bin/ash'

- name: Add a new user
  ansible.builtin.user:
    name: "{{ aok_user_name }}"
    # comment: John Doe
    uid: 501
    group: users
    shell: "{{ aok_user_shell }}"
    # password: "{{ 'abc123' | password_hash('sha512') }}"
    password: ''
    generate_ssh_key: true
    state: present
