---
#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  main toolbook
#

# - name: Show all gathered facts
#   hosts: all
#   vars_files:
#     - vars.yml
#   gather_facts: true
#   tasks:
#     - name: Display all facts
#       debug:
#         var: ansible_facts

- name: Setting up iSH FS
  hosts: "{{ target_hosts | default('localhost') }}"

  pre_tasks:
    - name: "Show version"
      ansible.builtin.debug:
        msg: "vers_ift = {{ vers_ift }}"

    - name: Load override variables
      ansible.builtin.import_tasks: tasks/load_overrides.yml

    - name: Verify parameters
      ansible.builtin.import_tasks: tasks/param_check.yml

  roles:
    - role: preparational_steps
    - role: alpine
      when: ansible_os_family == 'Alpine'
    - role: all_distros

  post_tasks:
    - name: "Change ownership of /opt/ish-fstools to {{ ift_user_name }}"
      ansible.builtin.file:
        path: /opt/ish-fstools
        owner: "{{ ift_user_name }}"
        group: "{{ ift_user_name }}"
        recurse: true
      when:
        - ift_user_name is defined
        - ift_user_name | length > 0
