---
#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025-2026: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Used to debug selected tasks
#

- name: Setting up iSH FS - limited dbg process
  vars:
    ansible_python_interpreter: /usr/bin/python3
  hosts: "{{ target_hosts | default('localhost') }}"
  gather_facts: false

  pre_tasks:
    - name: Prepare env to run playbooks
      # only disable skip_cloning when you want to skip cloning the repo
      vars:
        ift_quick_deploy: true
        # skip_cloning: true

      import_tasks: pre_tasks/main.yml
      tags: always

  #
  # only one of the below can be used - put the active one last
  #

  # #
  # # run specific task file
  # #
  # tasks:
  #   - name: Run specific task file
  #     import_tasks: tasks/restart_runbg.yml

  # #
  # # run specific task
  # #
  # tasks:
  #   - name: Intentional fail
  #     fail:
  #       msg: "Intentional fail"

  # #
  # # run specific task inside a role
  # #
  tasks:
    - name: Use just one task file from the role
      include_role:
        name: all_distros
        tasks_from: service_sshd.yml

  #
  # run specific role(-s)
  #
  # roles:
  #   #   - role: alpine
  #   #     when: ansible_facts.os_family == 'Alpine'
  #   - role: debian
  #     when: ansible_facts.os_family == 'Debian'
  # - role: all_distros

  # post_tasks:
  #   - name: Run tasks/update_release.yml
  #     import_tasks: tasks/update_release.yml
