---
#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  main toolbook
#

# - name: Show all gathered facts
#   hosts: all
#   vars_files:
#     - vars.yml
#   gather_facts: true
#   tasks:
#     - name: Display all facts
#       debug:
#         var: ansible_facts

- name: Setting up iSH FS
  hosts: "{{ target_hosts | default('localhost') }}"
  gather_facts: false
  pre_tasks:
    - name: Ensure Python is installed (and gather facts)
      import_tasks: tasks/install_python.yml
    - name: Load override variables
      import_tasks: tasks/pre_tasks.yml

  roles:
    - role: preparational_steps
    - role: alpine
      when: ansible_facts.os_family == 'Alpine'
    - role: debian
      when: ansible_facts.os_family == 'Debian'
    - role: all_distros

  post_tasks:
    - name: Run tasks/update_release.yml
      import_tasks: tasks/update_release.yml
