---
#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025-2026: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Used to debug selected tasks
#

- name: Setting up iSH FS - limited dbg process
  vars:
    ansible_python_interpreter: /usr/bin/python3
  hosts: "{{ target_hosts | default('localhost') }}"
  gather_facts: false

  # ============================================================
  #
  #     pre_tasks needs to always be run, to ensure python
  #     is installed, and to modify package variables depending
  #     on environment
  #
  # ============================================================
  pre_tasks:
    - name: Prepare env to run playbooks
      # only disable skip_cloning when you want to skip cloning the repo
      vars:
        ift_quick_deploy: true
        # skip_cloning: true

      import_tasks: pre_tasks/main.yml
      tags: always

  # ============================================================
  #
  #     Run a specific task file
  #
  # ============================================================
  # tasks:
  #   - name: Run specific task file
  #     import_tasks: tasks/restart_runbg.yml

  # ============================================================
  #
  #     Run a specific task
  #
  # ============================================================
  # tasks:
  #   - name: Check if openrc was used during boot-up
  #     import_tasks: tasks/was_openrc_used_to_boot_system.yml

  # ============================================================
  #
  #     Run specific task inside a role
  #
  # ============================================================
  # tasks:
  #   - name: Use just one task file from the role
  #     include_role:
  #       name: all_distros
  #       tasks_from: service_sshd.yml

  # ============================================================
  #
  #     Run specific role(-s)
  #
  # ============================================================
  roles:
    - role: common_handlers
    - role: initial_prep
    - role: alpine
      when: ansible_facts.distribution == 'Alpine'
  #   - role: debian
  #     when: ansible_facts.distribution == 'Debian'
  #   - role: all_distros
  #   - role: openrc
  #     when: ansible_facts.distribution in ['Alpine', 'Debian']
  #   - role: sysv_init
  #     when: ansible_facts.distribution == 'Devuan'

  # ============================================================
  #
  #     Run the post tasks
  #
  # ============================================================
  # post_tasks:
  #   - name: Run tasks/update_release.yml
  #     import_tasks: tasks/update_release.yml
