---
#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025-2026: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Used to debug selected tasks
#

- name: Setting up iSH FS
  hosts: "{{ target_hosts | default('localhost') }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    do_quick_deploy: true
    skip_cloning: true
  gather_facts: false

  handlers:
    - name: Import all handlers
      import_tasks: handlers/main.yml

  # ============================================================
  #
  #     pre_tasks needs to always be run, to ensure python
  #     is installed, and to modify package variables depending
  #     on environment
  #
  # ============================================================
  pre_tasks:
    - name: Prepare env to run playbooks
      import_tasks: pre_tasks/main.yml
      tags: always

  # ============================================================
  #
  #     Run a specific task
  #
  # ============================================================
  # tasks:
  #   - name: Check if openrc was used during boot-up
  #     import_tasks: tasks/was_openrc_used_to_boot_system.yml

  # ============================================================
  #
  #     Run specific task inside a role
  #
  # ============================================================
  # tasks:
  #   - name: Use just one task file from the role
  #     include_role:
  #       name: openrc
  #       tasks_from: service_monitor_sshd.yml

  # ============================================================
  #
  #     Run specific role(-s)
  #
  # ============================================================
  # roles:
  # - role: initial_prep

  # # FS specific tasks
  # - role: alpine
  #   when: ansible_facts.distribution == 'Alpine'
  # - role: debian
  #   when: ansible_facts.distribution == 'Debian'
  # - role: devuan
  #   when: ansible_facts.distribution == 'Devuan'

  # # FS generic tasks
  # - role: all_distros

  # Service handling, first type specific
  # - role: openrc
  #   when: ansible_facts.distribution in ['Alpine', 'Debian']
  # - role: sysv_init
  #   when: ansible_facts.distribution == 'Devuan'
  # - role: services # Service handling, common

  # ============================================================
  #
  #     Run the post tasks
  #
  # ============================================================
  # post_tasks:
  #   - name: Run tasks/update_release.yml
  #     import_tasks: tasks/update_release.yml
