---

#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  main toolbook
#

# - name: Show all gathered facts
#   hosts: all
#   vars_files:
#     - vars.yml
#   gather_facts: true
#   tasks:
#     - name: Display all facts
#       debug:
#         var: ansible_facts


- name: Setting up iSH FS
  hosts: all  # "{{ target_hosts }}"
  vars_files:
    - group_vars/all.yml  # default vars

  pre_tasks:
    - name: Include user override vars if present
      ansible.builtin.include_vars:
        file: group_vars/all.local.yml
      when: lookup('ansible.builtin.file', 'group_vars/all.local.yml',
                    errors='ignore') != ''

  roles:
    - role: preparational_steps
    - role: alpine
      when: ansible_os_family == 'Alpine'
    - role: all_distros
