---
#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  main toolbook
#

# - name: Show all gathered facts
#   hosts: all
#   vars_files:
#     - vars.yml
#   gather_facts: true
#   tasks:
#     - name: Display all facts
#       debug:
#         var: ansible_facts

- name: Setting up iSH FS
  hosts: "{{ target_hosts | default('localhost') }}"

  pre_tasks:
    - name: Load tasks/pre_tasks.yml
      ansible.builtin.import_tasks: tasks/pre_tasks.yml

  roles:
    - role: preparational_steps
    - role: alpine
      when: ansible_facts["os_family"] == 'Alpine'
    - role: all_distros

  post_tasks:
    - name: Run tasks/update_release.yml
      ansible.builtin.import_tasks: tasks/update_release.yml
