---
#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Used to debug selected tasks
#

- name: Setting up iSH FS - limited dbg process
  hosts: "{{ target_hosts | default('localhost') }}"

  pre_tasks:
    - name: "Show version"
      ansible.builtin.debug:
        msg: "vers_ift = {{ vers_ift }}"

    - name: Load override variables
      ansible.builtin.import_tasks: tasks/load_overrides.yml

    - name: Verify parameters
      ansible.builtin.import_tasks: tasks/param_check.yml

  #
  # only one of the below can be used - put the active one last
  #

  # #
  # # run specific task file
  # #
  # tasks:
  #   - name: Run specific task file
  #     ansible.builtin.include_tasks: tasks/is_ish.yml

  # #
  # # run specific task
  # #
  # tasks:
  #   - name: Intentional fail
  #     ansible.builtin.fail:
  #       msg: "Intentional fail"

  # #
  # # run specific task inside a role
  # #
  # tasks:
  #   - name: Use just one task file from the role
  #     ansible.builtin.include_role:
  #       name: all_distros
  #       tasks_from: service_sshd.yml

  #
  # run specific role(-s)
  #
  roles:
    - role: preparational_steps
    - role: alpine
      when: ansible_os_family == 'Alpine'
    # - role: all_distros
