---

#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Used to debug selected tasks
#

# - name: Show all gathered facts
#   hosts: all
#   vars_files:
#     - vars.yml
#   gather_facts: true
#   tasks:
#     - name: Display all facts
#       debug:
#         var: ansible_facts


- name: Setting up iSH FS
  hosts: "{{ target_hosts }}"
  vars_files:
    - vars.yml
  # only one of the below can be used!

  #
  # run specific role(-s)
  #
  roles:
    - role: all_distros

  #
  # run specific task(-s) inside a role
  #
  # tasks:
  #  - name: Include just root_shell.yml from the role
  #    ansible.builtin.include_role:
  #      name: all_distros
  #      tasks_from: root_shell.yml
  #    when: ift_user_shell is defined
