---

#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Used to debug selected tasks
#

- name: Setting up iSH FS
  hosts: "{{ target_hosts }}"
  vars_files:
    - vars.yml
  # only one of the below can be used!

  #
  # run specific role(-s)
  #
  # roles:
  #  - role: all_distros

  #
  # run specific task inside a role
  #
  tasks:
    - name: Include just root_shell.yml from the role
      ansible.builtin.include_role:
        name: all_distros
        tasks_from: disabling_default_services.yml
      when: ift_user_shell is defined
