#! /bin/sh

### BEGIN INIT INFO
# Provides:		sshd
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:
# Short-Description:	OpenBSD Secure Shell server
### END INIT INFO

# set -e # invalid due to ! conditions below

# /etc/init.d/ssh: start and stop the OpenBSD "secure shell(tm)" daemon

test -x /usr/sbin/sshd || exit 0
(/usr/sbin/sshd -\? 2>&1 | grep -q OpenSSH) 2>/dev/null || exit 0

umask 022

# shellcheck source=/dev/null
. /lib/lsb/init-functions

# Are we running from init?
run_by_init() {
    { [ -n "$previous" ] && [ -n "$runlevel" ]; } || [ "$runlevel" = S ]
}

check_dev_null() {
    if [ ! -c /dev/null ]; then
        if ! run_by_init; then
            log_action_msg "/dev/null is not a character device!" || true
        fi
        exit 1
    fi
}

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
    start)
        check_dev_null
        log_daemon_msg "Starting runbg server" "runbg" || true

        #  --quiet --oknodo --chuid 0:0 --exec
        # shell check disable=SC2086
        start-stop-daemon --start --background \
            --pidfile /run/runbg.pid \
            --startas /bin/cat -- /dev/location >/dev/null

        if $?; then
            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
        ;;

    stop)
        log_daemon_msg "Stopping OpenBSD Secure Shell server" "sshd" || true
        start-stop-daemon --stop --quiet --oknodo \
            --pidfile /run/runbg.pid \
            --exec /bin/cat
        if $?; then
            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
        ;;

    status)
        status_of_proc -p /run/runbg.pid /bin/cat runbg && exit 0 || exit $?
        ;;

    *)
        log_action_msg "Usage: /etc/init.d/runbg {start|stop|status}" || true
        exit 1
        ;;
esac

exit 0
