---
#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025-2026: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Services managed by openrc handling
#

- name: Check if openrc was used during boot-up
  import_tasks: ../tasks/was_openrc_used_to_boot_system.yml

- name: Run service_disabling_defaults.yml
  import_tasks: service_disabling_defaults.yml

- name: Create symbolic link for /etc/init.d/rc
  file:
    src: "{{ d_init_ift }}/rc"
    dest: "{{ d_init_d }}/rc"
    state: link
  when: ansible_facts.distribution == 'Debian'

- name: Deploy service runbg if requested
  import_tasks: service_runbg.yml
  when: b_deploy_runbg | default(false)

- name: Disable service runbg if not requested
  include_tasks: tasks/disable_service.yml # must be include to pass ansible-lint
  vars:
    srvc_name: runbg
  when: not b_deploy_runbg | default(false)

- name: Deploy service sshd if requested
  import_tasks: service_sshd.yml
  when: b_deploy_sshd | default(false)

# - name: Disable service sshd if not requested
#   include_tasks: tasks/disable_service.yml # must be include to pass ansible-lint
#   vars:
#     srvc_name: sshd
#   when: not b_deploy_sshd | default(false)
