---
#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025-2026: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Installs runbg service
#

- name: " runbg - Install service"
  copy:
    remote_src: true
    src: "{{ d_repo_openrc_role }}/files/etc/init.d/runbg"
    dest: "{{ d_init_ift }}/runbg"
    owner: root
    group: root
    mode: "0755"

- name: " runbg - Create symbolic link in /etc/init.d"
  file:
    src: "{{ d_init_ift }}/runbg"
    dest: "{{ f_service_runbg }}"
    state: link
  notify: Restart runbg

- name: " runbg - Set runlevel"
  include_tasks: tasks/service_runlevel_set.yml # should be include
  vars:
    srvc_name: "runbg"
    srvc_runlevel: "{{ ift_runlevel_runbg }}"
