---

#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Installs apps common for all Distros
#

- name: Install common additions for /usr/local/lib
  # become: true
  ansible.builtin.copy:
    mode: preserve
    remote_src: true
    src: "{{ d_repo_all_distros_role }}/files/usr_local_lib/"
    dest: /usr/local/lib/

- name: Install common additions for /usr/local/bin
  # become: true
  ansible.builtin.copy:
    mode: preserve
    remote_src: true
    src: "{{ d_repo_all_distros_role }}/files/usr_local_bin/"
    dest: /usr/local/bin/

- name: Install common additions for /usr/local/sbin
  # become: true
  ansible.builtin.copy:
    mode: preserve
    remote_src: true
    src: "{{ d_repo_all_distros_role }}/files/usr_local_sbin/"
    dest: /usr/local/sbin/
