---

#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Installs apps common for all Distros
#

- name: Common apps - Install to /usr/local/lib
  # become: true
  ansible.builtin.copy:
    mode: preserve
    remote_src: true
    src: "{{ d_repo_all_distros_role }}/files/usr_local_lib/"
    dest: /usr/local/lib/

- name: Deploy /usr/local/lib/ift-utils.sh with correct d_repo path
  ansible.builtin.template:
    src: ift-utils.sh.js2
    dest: /usr/local/lib/ift-utils.sh
    mode: '0755'

- name: Common apps - Install to  /usr/local/bin
  # become: true
  ansible.builtin.copy:
    mode: preserve
    remote_src: true
    src: "{{ d_repo_all_distros_role }}/files/usr_local_bin/"
    dest: /usr/local/bin/

- name: Common apps - Install to  /usr/local/sbin
  # become: true
  ansible.builtin.copy:
    mode: preserve
    remote_src: true
    src: "{{ d_repo_all_distros_role }}/files/usr_local_sbin/"
    dest: /usr/local/sbin/
