---

#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
# Various Distro neutral /etc configs
#

- name: Etc_configs Check if /etc/login.defs exists
  ansible.builtin.stat:
    path: /etc/login.defs
  register: login_defs_stat

- name: Etc_configs Set LOGIN_TIMEOUT in /etc/login.defs
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    line: 'LOGIN_TIMEOUT 0'
    insertafter: EOF
  when: login_defs_stat.stat.exists

- name: Etc_configs Install common config files
  become: true
  ansible.builtin.copy:
    mode: preserve
    remote_src: true
    src: "{{ d_all_distros }}/files/etc/{{ item }}"
    dest: "/etc/{{ item }}"
  loop:
    - environment
    - profile-hints

- name: Etc_configs Copy /etc/skel
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "{{ d_all_distros }}/files/etc/skel"
    dest: /etc
    owner: root
    group: root
    mode: '0644'

- name: Etc_configs Set /etc/issue for iSH node
  ansible.builtin.copy:
    dest: /etc/issue
    content: "This is an iSH node, running {{ ansible_distribution }}\n"
    owner: root
    group: root
    mode: '0644'

- name: Etc_configs Installing no-pw sudoers group
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "{{ d_all_distros }}/files/etc/sudoers.d/sudo_no_passwd"
    dest: /etc/sudoers.d
    owner: root
    group: root
    mode: '0644'

- name: Etc_configs Set system timezone to {{ ift_timezone }}
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ ift_timezone }}"
    dest: /etc/localtime
    state: link
    # force: true
  when:
    - ift_timezone is defined and ift_timezone
    - lookup(
        'ansible.builtin.fileglob',
        '/usr/share/zoneinfo/' ~ ift_timezone,
        errors='ignore'
      ) != ''
