---

#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#

- name: Common apps
  ansible.builtin.import_tasks: common_apps.yml

- name: Configs for /etc
  ansible.builtin.import_tasks: etc_configs.yml

# - name: Ensure /var/log/syslog exists
#   #  This task ensures that the syslog file exists, othewise the ift custom uptime
#   #  will
#   ansible.builtin.file:
#     path: /var/log/syslog
#     state: touch
#     owner: root
#     group: root
#     mode: '0644'

- name: Run timezone.yml
  ansible.builtin.import_tasks: timezone.yml
  when: ift_timezone is defined and ift_timezone

- name: Run disabling_default_services.yml
  ansible.builtin.import_tasks: disabling_default_services.yml

- name: Run service_dummy_sshd.yml
  ansible.builtin.import_tasks: service_dummy_sshd.yml
  when: ift_runlevel_sshd is defined and ift_runlevel_sshd

- name: Run service_runbg.yml
  ansible.builtin.import_tasks: service_runbg.yml
  when: ift_runlevel_runbg is defined and ift_runlevel_runbg

- name: Run user_account.yml
  ansible.builtin.import_tasks: user_account.yml
  when: ift_user_name is defined and ift_user_name

- name: Run root_shell.yml
  ansible.builtin.import_tasks: root_shell.yml
  when: ift_shell is defined and ift_shell

# =====   other   =====

# tasks:
#   setup_environment
#   set_hostname
#   setup_root_env
#   create_user
# Funcs:
#   user_shell
#   handle_hardcoded_tz
#   adding_runbg_service
#   removing_original_hostname_service
#   replacing_std_bins_with_aok_versions ""
#   changing_sshd_port

# setup_cron_env
