---

- name: Install common config files to /etc
  become: true
  ansible.builtin.copy:
    mode: preserve
    src: "files/{{ item }}"
    dest: "/etc/{{ item }}"
  loop:
    - environment
    - profile-hints

- name: Installing no-pw sudoers group
  become: true
  ansible.builtin.copy:
    mode: preserve
    remote_src: true
    src: "{{ d_common }}/etc/sudoers.d/sudo_no_passwd"
    dest: /etc/sudoers.d

- name: Copy /etc/skel
  become: true
  ansible.builtin.copy:
    # remote_src: true
    mode: preserve
    src: files/etc_skel/
    dest: /etc/skel

# user_shell
# handle_hardcoded_tz
# adding_runbg_service
# removing_original_hostname_service
# replacing_std_bins_with_aok_versions ""
# changing_sshd_port

# setup_cron_env

- name: Install common /usr/local/bin
  become: true
  ansible.builtin.copy:
    mode: preserve
    # remote_src: true
    src: files/usr_local_bin/
    dest: /usr/local/bin/

- name: Install common /usr/local/sbin
  become: true
  ansible.builtin.copy:
    mode: preserve
    # remote_src: true
    src: files/usr_local_sbin/
    dest: /usr/local/sbin/
