---

#
#  Copyright (c) 2025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Installs runbg service
#

- name: Check if this is iSH
  ansible.builtin.include_tasks: tasks/is_ish.yml
  when: vars['is_ish'] is not defined


- name: Set is_chrooted false when is_ish is true
  ansible.builtin.set_fact:
    is_chrooted: { "rc": 1, "stdout": "Skipped on is_ish", "stderr": "" }
  when: is_ish | default(false)

- name: Check if chrooted
  ansible.builtin.command: >
    sh -c '[ "$(uname -s)" != "Linux" ] && exit 1; ! grep -q " / / " /proc/self/mountinfo'
  register: is_chrooted
  changed_when: false
  when: not (is_ish | default(false))

- name: Was chrooted
  ansible.builtin.debug:
    msg: "{{ is_chrooted }}"

- name: Service runbg - install service
  # become: true
  ansible.builtin.copy:
    remote_src: true
    src: "{{ d_repo_all_distros_role }}/files{{ d_init_d }}/runbg"
    dest: "{{ d_init_ift }}/"
    owner: root
    group: root
    mode: '0755'

- name: Service runbg - create symbolic link
  ansible.builtin.file:
    src: "{{ d_init_ift }}/runbg"
    dest: "{{ service_runbg }}"
    state: link

- name: "Service runbg - Check if it is in runlevel: {{ ift_runlevel_runbg }}"
  ansible.builtin.shell: |
    set -o pipefail
    rc-status "{{ ift_runlevel_runbg }}" | grep -q '^ runbg'
  register: runbg_check
  changed_when: false
  failed_when: false

- name: Service runbg - Add to runlevel if needed
  ansible.builtin.command: rc-update add runbg "{{ ift_runlevel_runbg }}"
  when: runbg_check.rc != 0
  changed_when: true

- name: Service runbg - Restart it
  ansible.builtin.command: rc-service runbg restart
  changed_when: true
  when: is_chrooted.rc != 0
