---

#
#  Copyright (c) 025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Installs runbg service
#

- name: Service runbg - Copy service
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "{{ d_all_distros }}/files{{ d_init_d }}/runbg"
    dest: "{{ d_init_ift }}/"
    owner: root
    group: root
    mode: '0755'

- name: Service runbg - create symbolic link
  ansible.builtin.file:
    src: "{{ d_init_ift }}/runbg"
    dest: "{{ service_runbg }}"
    state: link

- name: Ensure 'runbg' is in 'sysinit' runlevel
  ansible.builtin.command: rc-update add runbg sysinit
  register: rc_update_result
  changed_when: "'Service added' in rc_update_result.stdout"
  failed_when: rc_update_result.rc != 0 and
               "'already in runlevel' not in rc_update_result.stdout"
