---

#
#  Copyright (c) 2025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Installs basic sshd service
#  This is a hack to make deploy on iSH much quicker, since doing it as  separate
#  tasks takes for ever and a day - see service_runbg.yml
#

- name: Check if sshd service is installed
  ansible.builtin.stat:
    path: "{{ d_init_d }}/sshd"
  register: stat_sshd_file

- name: Enable dummy sshd service
  ansible.builtin.shell: >
    mkdir -p "{{ d_init_ift }}" &&
    cp -av /etc/init.d/NOT/sshd "{{ d_init_ift }}" &&
    ln -sf "{{ d_init_ift }}/sshd" "{{ d_init_d }}" &&
    ln -sf "{{ d_init_ift }}/sshd" "/etc/runlevels/{{ ift_runlevel_sshd }}"
  when: not stat_sshd_file.stat.exists
