---

#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Imports overrides if vars/overrides.yml is found
#

- name: Check if override file exists
  ansible.builtin.stat:
    path: vars/overrides.yml
  register: overrides_file
  delegate_to: localhost
  run_once: true

- name: Read overrides file
  ansible.builtin.set_fact:
    __override_raw: "{{ lookup('file', 'vars/overrides.yml') }}"
  when: overrides_file.stat.exists
  delegate_to: localhost
  run_once: true

- name: Parse override vars
  ansible.builtin.set_fact:
    __override_vars: >-
      {{
        (__override_raw | from_yaml)
          if (__override_raw | trim) != ''
          else {}
      }}
  when: __override_raw is defined
  delegate_to: localhost
  run_once: true

- name: Extend ift_alpine_packages with extra packages
  ansible.builtin.set_fact:
    ift_alpine_packages: >-
      {{ (ift_alpine_packages | default([])) +
         (__override_vars.ift_extra_alpine_packages | default([])) }}
  when: __override_vars is defined
  delegate_to: localhost
  run_once: true

- name: Apply overrides
  ansible.builtin.set_fact:
    "{{ item.key }}": "{{ item.value }}"
  loop: "{{ __override_vars | dict2items }}"
  when: __override_vars is defined
  delegate_to: localhost
  run_once: true
