---
#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025-2026: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Ensures service is only in the intended runlevel(-s)
#
#  Variables required:
#     srvc_name     - name of service
#     srvc_runlevel - runlevel intended, if multiple should be used provide as a list
#

- name: "Service runlevel - Param check"
  fail:
    msg: "Both srvc_name & srvc_runlevel must be defined"
  when:
    - srvc_name is not defined or srvc_name | length == 0
    - srvc_runlevel is not defined or srvc_runlevel | length == 0

- name: "Ensure desired service runlevel for {{ srvc_name }}"
  shell: |
    set -o pipefail
    ex_code=0

    srvc_name=$(basename {{ srvc_name }})
    desired_runlevels="{{ srvc_runlevel | join(' ') }}"

    # Remove from undesired runlevels
    for rl in $(rc-status -l); do
        case " $desired_runlevels " in
            *" $rl "*) continue ;;
        esac

        if rc-status "$rl" | grep -qw "$srvc_name"; then
            rc-update del "$srvc_name" "$rl" || exit 30
            echo "removed from: $rl"
            ex_code=43
        fi
    done

    # Ensure in desired runlevels
    for rl in $desired_runlevels; do
        echo "already in [$rl]?"
        if ! rc-update show "$rl" | grep -q " $srvc_name"; then
            rc-update add "$srvc_name" "$rl" || exit 31
            echo "added to $rl"
            ex_code=43
        fi
    done

    exit $ex_code
  args:
    executable: /bin/bash
  register: srvc_runlevel_ensure
  changed_when: srvc_runlevel_ensure.rc == 43
  failed_when: srvc_runlevel_ensure.rc not in [0,43]
