---
#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025-2026: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Install selected Debian apps
#

- name: Remove packages listed in ift_debian_purges
  apt:
    state: absent
    purge: true
    autoremove: true
    pkg: "{{ ift_debian_purges | default([]) }}"

- name: Install selected packages listed in ift_debian_packages
  apt:
    state: present
    pkg: "{{ ift_debian_packages | default([]) }}"

- name: " opt/openssh - Install openssh tarball in /opt"
  unarchive:
    remote_src: true
    src: "{{ ift_openssh_tgz }}"
    dest: /

- name: Install abduco tarball in /usr/local
  unarchive:
    remote_src: true
    src: "{{ ift_abduco_tgz }}"
    dest: /

- name: "Install extras to /usr/local/bin  -- {{ remote_src_lbl }}"
  copy:
    remote_src: "{{ not b_old_ansible_detected }}"
    src: "{{ d_repo_debian_role }}/files/usr_local_bin/"
    dest: /usr/local/bin/
    mode: preserve

- name: "Install extras to /usr/local/sbin  -- {{ remote_src_lbl }}"
  copy:
    remote_src: "{{ not b_old_ansible_detected }}"
    src: "{{ d_repo_debian_role }}/files/usr_local_sbin/"
    dest: /usr/local/sbin/
    mode: preserve
