---
#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025-2026: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Role: Setup Debian
#

- name: Run apps_debian
  import_tasks: apps_debian.yml

- name: Install custom /etc/init.d/rc
  copy:
    remote_src: true
    src: "{{ d_repo_debian_role }}/files/etc/init.d/rc"
    dest: "{{ d_init_ift }}/rc"
    owner: root
    group: root
    mode: "0755"

- name: Generate required locales
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ ift_locales }}"

- name: Link the fake init to /sbin/init
  file:
    src: /usr/local/sbin/fake-init
    dest: /sbin/init
    state: link

- name: "Custom /etc/defaults/ssh"
  copy:
    remote_src: "{{ not b_old_ansible_detected }}"
    src: "{{ d_repo_debian_role }}/files/etc/defaults/ssh"
    dest: /etc/defaults
    mode: preserve
