---
#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025-2026: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Services managed by SysV init (init.d) handling
#

- name: Run service_runbg.yml
  import_tasks: service_runbg.yml
