#! /bin/sh

### BEGIN INIT INFO
# Provides:		runbg
# Required-Start:
# Required-Stop:
# Default-Start:	2 3 4 5
# Default-Stop:
# Short-Description:	GPS monitoring ensuring app continues in background
### END INIT INFO

# set -e # invalid due to ! conditions below

umask 022

# shellcheck source=/dev/null
. /lib/lsb/init-functions

# Are we running from init?
run_by_init() {
    { [ -n "$previous" ] && [ -n "$runlevel" ]; } || [ "$runlevel" = S ]
}

check_dev_null() {
    if [ ! -c /dev/null ]; then
        if ! run_by_init; then
            log_action_msg "/dev/null is not a character device!" || true
        fi
        exit 1
    fi
}

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
    start)
        check_dev_null
        log_daemon_msg "Starting runbg server" "runbg" || true
        if start-stop-daemon --start \
            --background \
            --make-pidfile \
            --pidfile /run/runbg.pid \
            --startas /bin/sh -- \
            -c 'exec /bin/cat /dev/location > /dev/null'; then

            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
        ;;

    stop)
        log_daemon_msg "Stopping runbg server" "runbg" || true
        if start-stop-daemon --stop \
            --pidfile /run/runbg.pid \
            --retry 5; then

            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
        ;;

    status)
        status_of_proc -p /run/runbg.pid /bin/cat runbg
        # exit $?
        ;;

    *)
        log_action_msg "Usage: /etc/init.d/runbg {start|stop|status}" || true
        exit 1
        ;;
esac

exit 0
