---
#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2026: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  All common handlers
#

#
#  Restart sshd
#
- name: When chrooted - fake restart sshd
  debug:
    msg: "Simulating service restart -->->   sshd   <-<--"
  changed_when: true
  when: not (is_ish | bool)
  listen: Restart sshd

- name: Restart service - sshd
  service:
    name: sshd
    state: restarted
  when:
    - is_ish | bool
    # - openrc_softlevel.stat.exists
  listen: Restart sshd

#
#  Restart runbg
#
- name: When chrooted - fake restart runbg
  debug:
    msg: "Simulating service restart -->->   runbg   <-<--"
  changed_when: true
  when: not (is_ish | bool)
  listen: Restart runbg

- name: Restart service - runbg
  service:
    name: runbg
    state: restarted
  when:
    - is_ish | bool
    # - openrc_softlevel.stat.exists
  listen: Restart runbg

#
#  Restart monitor-sshd
#

- name: When chrooted - fake restart monitor-sshd
  debug:
    msg: "Simulating service restart -->->   monitor-sshd   <-<--"
  changed_when: true
  when: not (is_ish | bool)
  listen: Restart monitor-sshd

- name: Restart via OpenRC - monitor-sshd
  service:
    name: monitor-sshd
    state: restarted
  when:
    - is_ish | bool
    # - openrc_softlevel.stat.exists
  listen: Restart monitor-sshd
