#!/bin/sh
#
#  Part of https://github.com/jaclu/AOK-Filesystem-Tools
#
#  License: MIT
#
#  Copyright (c) 2024: Jacob.Lundqvist@gmail.com
#
#  Displays iSH version
#

printf "\e[35m"
/usr/local/bin/ift-versions
printf "\e[0m"
