---

#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Install selected Alpine apps
#

- name: Display all Alpine packages being installed
  ansible.builtin.debug:
    msg: |
      Alpine packets to be installed:
      {% for pkg in ift_alpine_packages %}
        {{ pkg }}
      {% endfor %}

- name: Install selected packages
  # On my iPad: 1st run 3m10s, repeat 44s
  ansible.builtin.include_tasks: tasks/install_apk.yml
  vars:
    apk_packages: "{{ ift_alpine_packages }}"

- name: Install Alpine additions for /usr/local/bin
  # become: true
  ansible.builtin.copy:
    mode: preserve
    remote_src: true
    src: "{{ alpine_d_repo }}/files/usr_local_bin/"
    dest: /usr/local/bin/

- name: Install Alpine additions for /usr/local/sbin
  # become: true
  ansible.builtin.copy:
    mode: preserve
    remote_src: true
    src: "{{ alpine_d_repo }}/files/usr_local_sbin/"
    dest: /usr/local/bin/
