---

#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Configure Alpine F
#

- name: Deploy /etc/inittab
  # become: true
  ansible.builtin.copy:
    remote_src: true
    mode: preserve
    src: files/etc/inittab
    dest: /etc/
