#!/bin/sh
#
#  Part of https://github.com/jaclu/ish-fstool
#
#  Copyright (c) 2023-2025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Custom hostname, solving that iOS >= 17 no longer provides hostname
#  to Apps.
#
#  Working around regular iSH inability to use /etc/hostname with the native
#  hostname command.
#  Ensure this is in your PATH, before /bin
#

show_help() { # Multi OK 1
    [ -d /proc/ish ] || {
        echo
        echo "WARNING: this is only meaningful on iSH"
        echo
    }
    echo "Usage: hostname [-F|--file filename] [hostname]

Available options:

-h  --help         Print this help and exit

-F  --file         Read the host name from the specified file.

All other options are ignored, for compatibility with the default hostnme"
}

error_msg() {
    echo
    echo "ERROR[$0]: $1"
    echo

    exit 1
}

root_check() {
    [ "$(id -u)" -eq 0 ] || {
        error_msg "hostname: you must be root to change the host name"
    }
}

set_hostname() {
    new_hostname="$1"
    # f_hostname_override="/proc/ish/defaults/hostname_override"

    [ -z "$new_hostname" ] && error_msg "set_hostname() - no hostname param"
    root_check
    echo "$new_hostname" >"$f_etc_hostname" || {
        error_msg "Failed to write '$new_hostname' to '$f_etc_hostname'!"
    }
    # [ -f "$f_hostname_override" ] && {
    #     echo "'\"$new_hostname\"'" > "$f_hostname_override" || {
    #         error_msg "Failed to set $f_hostname_override"
    #     }
    #     override="$(cat "$f_hostname_override")"
    #     [ "$override" != "\"$new_hostname\"" ] && {
    #         error_msg "Failed to correctly set $f_hostname_override: [$override]"
    #     }
    # }
}

set_hostname_from_file() {
    f_new_hostname="$1"

    [ -z "$f_new_hostname" ] && {
        error_msg "No file specified for option '$1'!"
    }
    [ -f "$f_new_hostname" ] || {
        error_msg "No such file '$f_new_hostname'!"
    }
    [ -s "$f_new_hostname" ] || {
        error_msg "File '$f_new_hostname' is empty!"
    }
    wc -l "$f_new_hostname" | grep -q '^1 ' || {
        error_msg "File '$f_new_hostname' must contain exactly one line!"
    }
    root_check
    cp "$f_new_hostname" "$f_etc_hostname" || {
        error_msg "Failed to copy '$f_new_hostname' to '$f_etc_hostname'!"
    }
}

#===============================================================
#
#   Main
#
#===============================================================

f_etc_hostname=/etc/hostname

while [ -n "$1" ]; do
    case "$1" in
    "-h" | "--help")
        show_help
        exit 0
        ;;
    "-F" | "--file") set_hostname_from_file "$2" ;;
    -*) ;; # Ignore all other options, for compatibility with default hostname
    *) set_hostname "$1"  ;;
    esac
    shift
done

# actually displaying hostname
cat /etc/hostname
