#!/bin/sh
#
#  Part of https://github.com/jaclu/ish-fstool
#
#  Copyright (c) 2024-2025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Display installed versions of AOK-FS, File system being used
#  and ish-release
#

#
#  Display versions of deployed environment
#

# printf "\e[35m" # set color - magenta

if [ -f /etc/alpine-release ]; then
    echo "Alpine release:  $(cat /etc/alpine-release)"
elif [ -f /etc/devuan_version ]; then
    echo "Devuan version:  $(cat /etc/devuan_version)"
elif [ -f /etc/debian_version ]; then
    echo "Debian version:  $(cat /etc/debian_version)"
elif [ -f /etc/gentoo-release ]; then
    echo "Gentoo version:  $(cat /etc/gentoo-release)"
else
    echo "***  Failed to detect FS  ***"
fi

ish_version="$(cat /proc/ish/version 2>/dev/null)"
[ -z "$ish_version" ] && ish_version="can't be detected whilst chrooted"
echo "iSH release:     $ish_version"

aok_release="$(cat /etc/aok-fs-release 2>/dev/null)"
[ -z "$aok_release" ] && aok_release="Not found: /etc/aok-fs-release"
echo "AOK-FS release:  $aok_release"

# printf "\e[0m" # clear color
