#!/bin/sh
#
#  Part of https://github.com/jaclu/ish-fstool
#
#  License: MIT
#
# To minimize risk of running shutdown on a "real" Linux-node when using ssh this
# is somewhat of a safety alias
#
shutdown
