#!/bin/sh
#
#  Part of https://github.com/emkey1/AOK-Filesystem-Tools
#
#  License: MIT
#

# shellcheck source=/opt/ish-fstools/roles/all_distros/files/usr_local_lib/ift-utils.sh
. /usr/local/lib/ift-utils.sh

# execute again as root
if [ "$(whoami)" != "root" ]; then
    echo "Executing as root"
    # using $0 instead of full path makes location not hardcoded
    sudo "$0"
    exit 0
fi

echo "Removing VNC/X11 packages"
# shellcheck disable=SC2086  # in this case variable should expand
apk del $VNC_APKS

if [ -f /etc/X11/xorg.conf.d/10-headless.conf ]; then
    echo "Removing X11 headless config file"
    rm /etc/X11/xorg.conf.d/10-headless.conf
fi

echo "Leaving /etc/X11/Xwrapper.config.  You can delete it manually by typing 'sudo rm /etc/X11/Xwrapper.config' if so desired."
