#!/bin/sh
#
#  Part of https://github.com/jaclu/ish-fstool
#
#  License: MIT
#
#  Shutting down vnc-server if running
#

# pgrep fails when running Debian on iSH-AOK, so using grep for now...
# shellcheck disable=SC2009
if ps ax | grep -v grep | grep -q Xorg; then
    killall Xorg

    sleep 2

    echo
    echo "vnc server is now shut down"
else
    echo "vnc server was not running"
fi
