#! /bin/sh

### BEGIN INIT INFO
# Provides:		     runbg
# Required-Start:
# Required-Stop:
# Default-Start:	 2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: GPS monitoring ensuring app continues in background
# Description:       This service reads the GPS and discards the output to /dev/null.
#                    So this is not tracking you in any way. The sole purpose of this
#                    is that this is the only way to ensure an iOS program continues
#                    to run in the background.
#                    This process has no noticeable impact on battery life.
### END INIT INFO

# export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
DESC="runbg daemon"
NAME=runbg
PIDFILE="/run/runbg.pid"

# set -e # invalid due to ! conditions below
# umask 022

# shellcheck source=/dev/null
. /lib/lsb/init-functions

[ -d /proc/ish ] || {
    log_daemon_msg "runbg can only be run on iSH!"
    log_end_msg 1
    exit 1
}

# Are we running from init?
run_by_init() {
    { [ -n "$previous" ] && [ -n "$runlevel" ]; } || [ "$runlevel" = S ]
}

check_dev_null() {
    if [ ! -c /dev/null ]; then
        if ! run_by_init; then
            log_action_msg "/dev/null is not a character device!" || true
        fi
        exit 1
    fi
}

case "$1" in
    start)
        check_dev_null
        log_daemon_msg "Starting runbg server" "runbg"
        start-stop-daemon --start \
            --background \
            --make-pidfile \
            --pidfile "$PIDFILE" \
            --startas /bin/sh -- \
            -c 'exec /bin/cat /dev/location > /dev/null'
        log_end_msg "$?"
        ;;

    stop)
        log_daemon_msg "Stopping runbg server" "runbg"
        start-stop-daemon --stop --pidfile "$PIDFILE" --retry 5
        log_end_msg "$?"
        ;;

    restart)
        log_daemon_msg "Restarting $DESC" "$NAME"
        $0 stop && $0 start
        ;;

    reload | force-reload)
        log_daemon_msg "Reloading $DESC (has no impact)" "$NAME"
        log_end_msg 0
        ;;

    status)
        status_of_proc -p "$PIDFILE" /bin/cat runbg
        exit $?
        ;;

    *)
        _s="{start|stop|restart|reload|force-reload|status}"
        log_action_msg "Usage: /etc/init.d/runbg $_s"
        exit 1
        ;;
esac
