---
#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025-2026: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Role: preparational_steps - Verify that params are sane
#   Do this before base apks are installed to trigger early abort
#  what will be installed / purged has already been decided via process_overrides.yml
#  so the list of packages to be installed can be seen as completed.
#

#
#  All Distros
#

- name: Param checks - Fail if user_name is defined, but not ift_shell
  fail:
    msg: "ift_shell must be defined when user_name is set"
  delegate_to: localhost
  run_once: true
  when:
    - user_name | default('') | length > 0
    - (ift_shell is not defined) or ift_shell | default('') | length == 0

- name: Param checks - Verify ift_runlevel_runbg is a list
  ansible.builtin.assert:
    that:
      - ift_runlevel_runbg is not none
      - ift_runlevel_runbg is sequence
      - ift_runlevel_runbg is not string
    fail_msg: "ift_runlevel_runbg must be a list, not null or another type"
    quiet: true
  delegate_to: localhost
  run_once: true

- name: Param checks - Verify ift_runlevel_sshd is a list
  ansible.builtin.assert:
    that:
      - ift_runlevel_sshd is not none
      - ift_runlevel_sshd is sequence
      - ift_runlevel_sshd is not string
    fail_msg: "ift_runlevel_sshd must be a list, not null or another type"
    quiet: true
  delegate_to: localhost
  run_once: true

- name: Param checks - Run param_checks_alpine.yml
  import_tasks: param_checks_alpine.yml
  when: ansible_facts.distribution == 'Alpine'

- name: Param checks - Run param_checks_debian.yml
  import_tasks: param_checks_debian.yml
  when: ansible_facts.distribution == 'Debian'

- name: Param checks - Run param_checks_devuan.yml
  import_tasks: param_checks_debian.yml
  when: ansible_facts.distribution == 'Devuan'
