---

#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Role: preparational_steps - main tasks
#

# skipping iSH check for now, atm nothing in deploy needs it, but will leave it in
# since it might be handy later
# - name: Check if this is iSH
#   ansible.builtin.include_tasks: tasks/is_ish.yml
#   when: vars['is_ish'] is not defined

- name: Ensure iSH can run in the background
  # This is just for first deploy, during install a service doing this
  # each time iSH is started will be installed & started
  ansible.builtin.shell: |
    if [ -d /proc/ish ]; then
      (nohup cat /dev/location > /dev/null 2>&1 </dev/null & sleep 0.1)
    fi
  changed_when: false
  # when: is_ish

- name: Package upgrade
  ansible.builtin.package:
    update_cache: true
    upgrade: true

- name: Ensure crucial apps needed for 1st deploy are available
  ansible.builtin.package:
    state: present
    name:
      - git
      - rsync

- name: Checkout ish-fstools into /opt
  ansible.builtin.git:
    repo: https://github.com/jaclu/ish-fstools.git
    dest: /opt/ish-fstools
    version: main
