---

#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Role: preparational_steps - main tasks
#

# skipping iSH check here, since on iSH it is really slow, and not needed in
# this playbook

- name: Check if iSH is background enabled
  ansible.builtin.shell: |
    [ -d /proc/ish ] && pgrep -af 'cat /dev/location'
  register: cat_location_proc
  changed_when: false
  failed_when: false

# - name: Display cat_location_proc
#   ansible.builtin.debug:
#     msg: "{{ cat_location_proc }}"

- name: Ensure iSH can run in the background
  # This is just for first deploy, during install a service doing this
  # each time iSH is started will be installed & started
  ansible.builtin.shell: |
    if [ -d /proc/ish ]; then
      (nohup cat /dev/location > /dev/null 2>&1 </dev/null & sleep 0.1)
    fi
  changed_when: false
  when: cat_location_proc.stdout == ''

- name: "Ensure  directory exists: {{ d_etc_ift }}"
  ansible.builtin.file:
    path: "{{ d_etc_ift }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: "Add the Alpine testing repo if at least v{{ ift_alpine_testing_repo_minv }}"
  # become: true
  ansible.builtin.lineinfile:
    path: /etc/apk/repositories
    line: 'https://dl-cdn.alpinelinux.org/alpine/edge/testing'
    insertafter: EOF
  when:
    - ansible_os_family == 'Alpine'
    - ansible_distribution_version is version(ift_alpine_testing_repo_minv, '>=')

- name: Package upgrade
  ansible.builtin.package:
    update_cache: true
    upgrade: true

- name: Ensure crucial apps needed for 1st deploy are available
  ansible.builtin.package:
    state: present
    name:
      - git
      - rsync
      - bash

- name: Checkout ish-fstools into /opt
  ansible.builtin.git:
    repo: https://github.com/jaclu/ish-fstools.git
    dest: /opt/ish-fstools
    version: main
