---
#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025-2026: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  SysV init (init.d) handling of sshd
#

- name: " sshd conf - Install /etc/ssh/sshd_config"
  template:
    src: sshd_config.js2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0755"

- name: " sshd conf - Remove all unintended Port lines"
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^[Pp]ort\s+(?!{{ ift_port_sshd | default(2022) }}\b).*'
    replace: ""

- name: " sshd conf - Deduplicate intended Port lines"
  shell: |
    f_tmp=$(mktemp "${TMPDIR:-/tmp}"/deduplicate-sshd-ports.XXXXXX)
    awk '
      /^Port {{ ift_port_sshd | default(2022) }}/ {
        if (!seen++) { print; next }
        next
      }
      { print }
    ' /etc/ssh/sshd_config > "$f_tmp" || {
      rm -f "$f_tmp"
      exit 30
    }
    if ! cmp -s /etc/ssh/sshd_config "$f_tmp"; then
      mv "$f_tmp" /etc/ssh/sshd_config || {
        rm -f "$f_tmp"
        exit 31
      }
      exit 43
    else
      rm -f "$f_tmp"
    fi
  args:
    executable: /bin/bash
  register: services_sshd_port_dupes
  changed_when: services_sshd_port_dupes.rc == 43
  failed_when: services_sshd_port_dupes.rc not in [0, 43]

- name: " sshd conf - Ensure intended Port line is present once"
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "Port {{ ift_port_sshd | default(2022) }}"
    regexp: "^Port {{ ift_port_sshd | default(2022) }}"
    state: present
