---
#
#  Part of https://github.com/jaclu/ish-fstools
#
#  Copyright (c) 2025-2026: Jacob.Lundqvist@gmail.com
#
#  License: MIT
#
#  Role: Setup Devuan
#
#  Devuan shares init scripts and helper binaries with the Debian role
#  since both use OpenRC on iSH.
#

- name: Run apps_devuan
  import_tasks: apps_devuan.yml

- name: Install custom /etc/init.d/rc
  copy:
    remote_src: true
    src: "{{ d_repo_debian_role }}/files/etc/init.d/rc"
    dest: "{{ d_init_ift }}/rc"
    owner: root
    group: root
    mode: "0755"

- name: Generate required locales
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ ift_locales }}"

- name: Install inittab
  copy:
    src: "{{ d_repo_devuan_role }}/files/etc/inittab"
    dest: /etc/inittab
    owner: root
    group: root
    mode: "0644"
    remote_src: true

- name: " opt/openssh - Install Debian sshd_config"
  template:
    src: sshd_config.js2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0755"
